### ISSUE TITLE
Photo blank if I turn off ZSL and choose auto focus mode

### ISSUE THREAD

**Issue by YumeMichi** [kerneltoast/android_packages_apps_Snap#2]
I don't know whether this is a bug of Snap or CameraHAL.

Screenshot:
![](https://blog.ikke.moe/img/Screenshot_20160603-223937.png)

Photo:
![](https://blog.ikke.moe/img/IMG_20160603_223943.jpg)

**Comment by kerneltoast** [comment]
I don't have this issue. If it is a problem, then it's related to the camera HAL, not Snap.
